# Use the official Python image from the Docker Hub
FROM python:3.9-slim


# Create and set the working directory
WORKDIR /app

# Copy the requirements file
# COPY requirements.txt .

# Install the Python dependencies
RUN pip install fastapi uvicorn requests pydantic

# Copy the rest of the application code
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8084

# Run the FastAPI application using uvicorn
CMD ["uvicorn", "securityAgent:app", "--host", "0.0.0.0", "--port", "8084"]
